name: homework_4
description: homework_4

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # widgets
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flutter_html: ^2.2.1

  # http
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1

  # generators
  json_annotation: 4.4.0
  flutter_bloc: ^8.0.1

dev_dependencies:
  dart_style: 2.2.1

  # generators
  build_runner: 2.1.7
  json_serializable: 6.1.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
